config/routes.rb
Rails.application.routes.draw do

  resources :home
  resources :companies
  resources :projects
  resources :clients
  resources :employees
  resources :works
  resources :sessions  
  root to: 'sessions#new'

  get 'login', to: 'sessions#new'  
  get '/auth/failure', to: 'sessions#failure'
  get '/oauth2callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/session_expired', to: 'sessions#expired', as: 'session_expired'
  post '/refresh_token', to: 'sessions#refresh_token'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
	# Associations
	belongs_to :company
	has_many :works
	has_many :projects, :through => :works

	#db validations
	validates :name, presence: true
  validates :company_id, presence: true
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	def index
		@employees = Employee.all
	end

	def show
		if params[:id]
			if Employee.exists?(params[:id])
				@employee =  Employee.find(params[:id])
			end
		elsif params[:slug]
			if Employee.find_by username: params[:slug]
				@employee = Employee.find_by username: params[:slug]
				@employee_works = @employee.works.paginate(:page => params[:page], :per_page => 10)
			else
				render :"errors/notfound"
			end
		end
	end

	#Controller to get the Employee work details
	def work
		if params[:id]
			if Employee.exists?(params[:id])
				@employee = Employee.find(params[:id])
				@employee_works = @employee.works.paginate(:page => params[:page], :per_page => 10)
			else
				render :"errors/notfound"
			end
		end
	end

	#Controller to add new Employee
	def new
		@employee = Employee.new
	end

	#Controller to save new Employee record
	def create
		@employee = Employee.new(user_params)
		if @employee.valid?
			@employee.save
			flash[:notice] = "Successfully added new Employee"
			redirect_to @employee
		else
			render 'new'
		end
	end

	#Edit employee controller
	def edit
		@employee = Employee.find(params[:id])
	end

	#Update employee records
	def update
		@employee = Employee.find(params[:id])
		if @employee.update(user_params)
			flash[:notice] = "Successfully Updated Employee details"
			redirect_to @employee
		else
			render 'edit'
		end
	end

	#Delete Employee record
	def destroy
	    @employee = Employee.find(params[:id])
	    if @employee.destroy
	      flash[:notice] = "Employee deleted Successfully"
	      redirect_to @employee
	    else
	      flash[:notice] = "Error in deleting the Employee"
	      redirect_to @employee
	    end
  	end

   private
    def user_params
      params[:employee].permit(:company_id, :name)
    end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_actions.haml
.row
  = link_to 'Add New', new_employee_path(@employee), class: "btn btn-info pull-right"

app/views/employees/_form.haml
-if @employee.errors.any?
  .alert.alert-danger{:role => "alert"}
    %p Please fix the following #{pluralize(@employee.errors.count, "error")}:
    %ul
      - @employee.errors.full_messages.each do |msg|
        %li= msg

%h1= (@employee.new_record? ? "Add New Employee" : "Edit Employee details")
.row
  .span6.offset3
    = form_for(@employee) do |e|
      %div
        = e.label :name
        = e.text_field :name
      %div
        = e.label :company_id
        = e.collection_select(:company_id, Company.all.order('name'), :id, :name, prompt: true)
      %div
        = e.submit (@employee.new_record? ? "Add" : "Update"), class: "btn btn-large btn-primary"

app/views/employees/_index.haml
- @employees.each do |employee|
  %tr
    %td= link_to employee.name, employee

app/views/employees/_sidebar.haml
-#Sidebar
%h5 Quick Links
%ul.list-group 
  %li.list-group-item= link_to "Employees", employees_path  
  %li.list-group-item= link_to "Add new Employee", new_employee_path
  %li.list-group-item= link_to "Add new Work", new_work_path

app/views/employees/edit.haml
-#Head section
- content_for :head do
  %title Edit #{@employee} details

-#Form
= render "form"

-#Sidebar
- content_for(:aside) do
  = render "sidebar"

app/views/employees/index.haml
- content_for :head do
  %title Employees Information

/ Action Bar
= render "actions"

%h4 Employees Information
.row
  .col-xs-4.col-sm-3    
    .table-responsive  
      %table.table.table-striped.table-hover    
        %thead
          %tr
            %th Name
        %tbody
          = render "index"

- content_for(:aside) do
  = render "sidebar"

app/views/employees/new.haml
-#Head section
- content_for :head do
  %title Add new Employee

-# Form
= render "form"

-#Sidebar
- content_for(:aside) do
  = render "sidebar"

app/views/employees/show.haml
- content_for :head do
  %title #{@employee} details

%h4 Employee Details
%div{:class => "btn-group"}
  %button{:type => "button", :class => "btn btn-info dropdown-toggle", data: {toggle: "dropdown"}}
    Update
    %span{:class => "caret"}
    
  %ul{:class => "dropdown-menu", :role => "menu"}
    %li= link_to "Edit", edit_employee_path(@employee)
    %li= link_to "Delete", @employee, :method => "delete", data: { confirm: "Are You sure?" }

%hr
= image_tag "empty_profile_male.jpg", alt: "Profile", class: "img-circle", size: "140x140"
%ul  
  %li 
    %strong Employee Name:
    = @employee.name+" "+@employee.name

%hr
- content_for :aside do
  = render "sidebar"

app/views/employees/work.haml
- content_for :head do
  %title #{@employee} work details

%strong Work Details
%table.table.table-hover
  %thead
    %tr
      %th Employee
      %th Project
      %th Client
      %th Date time
      %th Hours
  %tbody
    = render partial: "works/works", collection: @employee_works    
= will_paginate @employee_works

- content_for(:aside) do
  = render "sidebar"