config/routes.rb
Rails.application.routes.draw do

  resources :home
  resources :companies
  resources :projects
  resources :clients
  resources :employees
  resources :works
  resources :sessions  
  root to: 'sessions#new'

  get 'login', to: 'sessions#new'  
  get '/auth/failure', to: 'sessions#failure'
  get '/oauth2callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/session_expired', to: 'sessions#expired', as: 'session_expired'
  post '/refresh_token', to: 'sessions#refresh_token'

end

app/models/client.rb
class Client < ActiveRecord::Base
	# Associations
	belongs_to :company
	has_many :projects

	#db validations
	validates :name, presence: true, uniqueness: true
  	validates :company_id, presence: true
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    def index
        @clients = Client.all
    end

    def show
      if (params[:id])
        if Client.exists?(params[:id])
          @client =  Client.find(params[:id])
          @client_projects = @client.projects.paginate(:page => params[:page], :per_page => 10)
        else
          render :"errors/notfound"
        end
      end
    end

    #Controller to add new Client
    def new
      @client = Client.new
    end

    #Controller to save new Client
    def create
      @client = Client.new(user_params)
      if @client.valid?
        @client.save
        flash[:notice] = "Successfully added new client"
        redirect_to @client
      else
        render 'new'
      end
    end

    #Edit client
    def edit
      @client = Client.find(params[:id])
    end

    #Update client records
    def update
      @client = Client.find(params[:id])

      if @client.update(user_params)
        flash[:notice] = "Successfully updated the client"
        redirect_to @client
      else
        render 'edit'
      end
    end

    #Delete company records
    def destroy
      @client = Client.find(params[:id])
      if @client.destroy
        flash[:notice] = "Client deleted Successfully"
        redirect_to @client
      else
        flash[:notice] = "Error in deleting the Client"
        redirect_to @client
      end
    end

    private
      def user_params
        params[:client].permit(:name, :company_id)
      end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_actions.haml
.row
  = link_to 'Add New', new_client_path(@client), class: "btn btn-info pull-right"

app/views/clients/_form.haml
- if @client.errors.any?
  .alert.alert-danger{:role => "alert"}
    %p Please fix the following #{pluralize(@client.errors.count, "error")}
    %ul
      - @client.errors.full_messages.each do |msg|
        %li= msg

%h1= (@client.new_record? ? "Add new Client" : "Update Client details")
.row
  .span6.offset3
    = form_for(@client) do |c|
      %div
        = c.label :name, 'Client Name'
        = c.text_field :name
      %div
        = c.label :company_id
        = c.collection_select(:company_id, Company.all.order('name'), :id, :name, prompt: true)
      %div
        = c.submit (@client.new_record? ? "Add" : "Update"), class: "btn btn-large btn-primary"

app/views/clients/_index.haml
- @clients.each do |client|
  %tr
    %td= link_to client.name, client

app/views/clients/_sidebar.haml
%h5 Quick Links
%ul.list-group 
	%li.list-group-item= link_to "Clients", clients_path
	%li.list-group-item= link_to "Projects", projects_path
	%li.list-group-item= link_to "Add new Client", new_client_path

app/views/clients/edit.haml
-#Head section
- content_for :head do
  %title Edit #{@client.name} work details

-#Form
= render "form"

-#Sidebar
- content_for(:aside) do
  = render "sidebar"

app/views/clients/index.haml
- content_for :head do
  %title Clients Information
/ Action Bar
= render "actions"

%h4 Clients information
.row
  .col-xs-4.col-sm-3    
    .table-responsive  
      %table.table.table-striped.table-hover    
        %thead        
          %tr
            %th Name
        %tbody
          = render "index"

- content_for(:aside) do
  = render "sidebar"

app/views/clients/new.haml
-#Head section
- content_for :head do
  %title Add new Client

-#Form
= render "form"

-#Sidebar
- content_for(:aside) do
  = render "sidebar"

app/views/clients/show.haml
- content_for :head do
  %title #{@client.name} details

%h4 Client Details
%div{:class => "btn-group"}
  %button{:type => "button", :class => "btn btn-info dropdown-toggle", data: {toggle: "dropdown"}}
    Update
    %span{:class => "caret"}
    
  %ul{:class => "dropdown-menu", :role => "menu"}
    %li= link_to "Edit", edit_client_path(@client)
    %li= link_to "Delete", @client, :method => "delete", data: { confirm: "Are You sure?" }

%hr
%p
  %strong Client:
  = @client.name
%p
  %strong Company
  = @client.company.name

- content_for :aside do
  = render "sidebar"