config/routes.rb
Rails.application.routes.draw do

  resources :home
  resources :companies
  resources :projects
  resources :clients
  resources :employees
  resources :works
  resources :sessions  
  root to: 'sessions#new'

  get 'login', to: 'sessions#new'  
  get '/auth/failure', to: 'sessions#failure'
  get '/oauth2callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/session_expired', to: 'sessions#expired', as: 'session_expired'
  post '/refresh_token', to: 'sessions#refresh_token'

end

app/models/project.rb
class Project < ActiveRecord::Base
	#Associations	
	belongs_to :client
	has_many :employees
	has_many :works

	#add validations
	validates :name, presence: true, uniqueness: true
  	validates :client_id, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  #Show controller
  def show
    if params[:id]
      if Project.exists?(params[:id])
        @project =  Project.find(params[:id])
      else
       render :"errors/notfound"      
      end
    end
  end

  #Works controller
  def works
    if (params[:id])
      if Project.exists?(params[:id])
        @project = Project.find(params[:id])
        @project_works = @project.works.paginate(:page => params[:page], :per_page => 10)
      else
        render :"errors/notfound"
      end
    end
  end

  #Controller to add new Project
  def new
    @project = Project.new
  end 

  #Controller to save the new Project
  def create
    @project = Project.new(params[:project].permit(:name, :default_rate, :company_id, :client_id))
    if @project.valid?
      @project.save
      flash[:notice] = "Successfully created new Project"
      redirect_to @project
    else
      render 'new'
    end
  end

  #Edit Project
  def edit
    @project = Project.find(params[:id])
  end

  #Update Project details
  def update
    @project = Project.find(params[:id])
    if @project.update(params[:project].permit(:name, :default_rate, :company_id, :client_id))
      flash[:notice] = "Successfully Updated Project details"
      redirect_to @project
    else
      render 'edit'
    end
  end

  #Delete Project details
  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      flash[:notice] = "Project deleted Successfully"
      redirect_to @project
    else
      flash[:notice] = "Error in deleting the Project"
      redirect_to @project
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_actions.haml
.row
  = link_to 'Add New', new_project_path(@project), class: "btn btn-info pull-right"

app/views/projects/_form.haml
-if @project.errors.any?
  .alert.alert-danger{:role => "alert"}
    %p Please fix the following #{pluralize(@project.errors.count, "error")}:
    %ul
    - @project.errors.full_messages.each do |msg|
      %li= msg

%h1= (@project.new_record? ? "Add new Project" : "Update Project")
.row
  .span6.offset3
    = form_for(@project) do |p|
      %div
        = p.label :name, 'Project Name'
        = p.text_field :name      
      %div
        = p.label :client_id
        = p.collection_select(:client_id, Client.all.order('name'), :id, :name, prompt: true)
      %div
        = p.submit (@project.new_record? ? "Add" : "Update"), class: "btn btn-large btn-primary"

app/views/projects/_index.haml
- @projects.each do |project|
  %tr
    %td= link_to project.name, project

app/views/projects/_sidebar.haml
%h5 Quick Links
%ul.list-group 
  %li.list-group-item= link_to "All Projects", projects_path
  %li.list-group-item= link_to "Add New Project", new_project_path
  %li.list-group-item= link_to "Add new Work", new_work_path

app/views/projects/edit.haml
-#Head Section
- content_for :head do
  %title Edit #{@project.name} details

-#Form
= render "form"

-#Sidebar
- content_for(:aside) do
  = render "sidebar"

app/views/projects/index.haml
- content_for :head do
  %title Projects Information
/ Action Bar
= render "actions"

%h4 All Projects
.row
  .col-xs-4.col-sm-3    
    .table-responsive  
      %table.table.table-striped.table-hover        
        %thead
          %tr
            %th Project
        %tbody
          = render "index"

- content_for (:aside) do
  = render "sidebar"

app/views/projects/new.haml
-#Head section
- content_for :head do
  %title Add new Project

-#Form
= render "form"

-#Sidebar
- content_for(:aside) do
  = render "sidebar"

app/views/projects/show.haml
- content_for :head do
  %title #{@project.name} Details

%h4 Project Details
%div{:class => "btn-group"}
  %button{:type => "button", :class => "btn btn-info dropdown-toggle", data: {toggle: "dropdown"}}
    Update
    %span{:class => "caret"}
    
  %ul{:class => "dropdown-menu", :role => "menu"}
    %li= link_to "Edit", edit_project_path(@project)
    %li= link_to "Delete", @project, :method => "delete", data: { confirm: "Are You sure?" }

%hr
%p
  %ul
    %li
      %strong Project Name: 
      #{@project.name}

- content_for(:aside) do
  = render "sidebar"