config/routes.rb
Rails.application.routes.draw do

  resources :home
  resources :companies
  resources :projects
  resources :clients
  resources :employees
  resources :works
  resources :sessions  
  root to: 'sessions#new'

  get 'login', to: 'sessions#new'  
  get '/auth/failure', to: 'sessions#failure'
  get '/oauth2callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/session_expired', to: 'sessions#expired', as: 'session_expired'
  post '/refresh_token', to: 'sessions#refresh_token'

end

app/models/company.rb
class Company < ActiveRecord::Base
	# Associations
	has_many :clients
	has_many :employees

	#db validations
	validates :name, presence: true, uniqueness: true  	
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
    #render json: @companies
  end

  #Show controller
  def show
    if params[:id]
      if Company.exists?(params[:id])
        @company = Company.find(params[:id])
      else
        render :"errors/notfound"
      end
    end
  end

  #Controller to add new Company
  def new
    @company = Company.new
  end

  #Controller to save new Company
  def create
    @company = Company.new(user_params)
    if @company.valid?
      @company.save
      flash[:notice] = "Successfully updated Company"
      redirect_to @company
    else
      render 'new'
    end
  end

  #Cotnroller to edit
  def edit
    @company = Company.find(params[:id])
  end

  #Update company records
  def update
    @company = Company.find(params[:id])
    if @company.update(user_params)
      flash[:notice] = "Successfully updated Company"
      redirect_to @company
    else
      render 'edit'
    end
  end

  #Delete company record
  def destroy
    @company = Company.find(params[:id])
    if @company.destroy
      flash[:notice] = "Company deleted Successfully"
      redirect_to @company
    else
      flash[:notice] = "Error in deleting the Company"
      redirect_to @company
    end
  end

  private
    def user_params
      params[:company].permit(:name)
    end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_actions.haml
.row
  = link_to 'New', new_company_path(@company), class: "btn btn-info pull-right"

app/views/companies/_form.haml
- if @company.errors.any?
  .alert.alert-danger{:role => "alert"}
    %p Please fix the following #{pluralize(@company.errors.count, "error")}
    %ul
      - @company.errors.full_messages.each do |msg|
        %li= msg

%h1= (@company.new_record? ? "Add new Company" : "Update Employee details")
.row
  .span6.offset3
    = form_for(@company) do |f|
      = f.label :name
      = f.text_field :name
      = f.submit (@company.new_record? ? "Add" : "Update"), class: "btn btn-large btn-primary"

app/views/companies/_index.haml
- @companies.each do |compnay|
  %tr
    %td= link_to compnay.name, compnay

app/views/companies/_sidebar.haml
%h5 Quick Links
%ul.list-group 
	%li.list-group-item= link_to "Companies", companies_path
	%li.list-group-item= link_to "Clients", clients_path
	%li.list-group-item= link_to "Projects", projects_path
	%li.list-group-item= link_to "Employees", employees_path
	%li.list-group-item= link_to "Works", works_path
	%li.list-group-item= link_to "Add new Company", new_company_path

app/views/companies/edit.haml
-#Head section
- content_for :head do
  %title Edit #{@company.name} details

-#Form 
= render "form"

-#Sidebar
- content_for(:aside) do
  = render "sidebar"

app/views/companies/index.haml
- content_for :head do
  %title Companies Information
/ Action Bar
= render "actions"

%h4 Companies Information
.row
  .col-xs-4.col-sm-3    
    .table-responsive  
      %table.table.table-striped.table-hover    
        %thead        
          %tr
            %th Name
        %tbody
          = render "index"

- content_for(:aside) do
  = render "sidebar"

app/views/companies/new.haml
-#Head section
- content_for :head do
  %title Add new Company

-#Form
= render "form"

-#Sidebar
- content_for(:aside) do
  = render "sidebar"

app/views/companies/show.haml
- content_for :head do
  %title #{@company.name} details

%h4 Compnay Details
%div{:class => "btn-group"}
  %button{:type => "button", :class => "btn btn-info dropdown-toggle", data: {toggle: "dropdown"}}
    Update
    %span{:class => "caret"}
    
  %ul{:class => "dropdown-menu", :role => "menu"}
    %li= link_to "Edit", edit_company_path(@company)
    %li= link_to "Delete", @company, :method => "delete", data: { confirm: "Are You sure?" }

%hr
%p
  %strong Company Name:
  = @company.name
  
%br
- content_for :aside do
  = render "sidebar"